import ArticleImage from "@/assets/image/ArticleImage.png";

export const POSTS = [
  {
    id: 0,
    image: ArticleImage,
    tags: ["technology", "tech", "career"],
    tag: "FEATURED ARTICLE",
    title: "Culpa sit Laboris Exercitation ea Fugiat",
    artist: "Arthur Black",
    artistNickName: "arthurblack",
    date: "May 7, 2019",
    text: "Commodo labore ut nisi laborum amet eu qui magna ullamco ut labore. Aliquip consectetur labore consectetur dolor exercitation est minim quis. Magna non irure qui ex est laborum nulla excepteur qui. Anim Lorem dolore cupidatat pariatur ex tempor. Duis ea excepteur proident ex commodo irure est.Nisi commodo qui pariatur enim sint laborum consequat enim in officia. Officia fugiat incididunt commodo et mollit aliqua non aute. Enim dolor eiusmod aliqua amet ipsum in enim eiusmod. Quis exercitation sit velit duis.Est Lorem labore consectetur minim sit eu eiusmod mollit velit. Consectetur voluptate ex amet id eiusmod laborum irure. Aliquip ad qui id exercitation irure amet commodo nisi quis. Occaecat minim incididunt eiusmod nostrud veniam quis culpa.Nisi ipsum et consequat id deserunt excepteur. Cillum non pariatur culpa ut occaecat laboris eu. Ullamco ad Lorem et elit laboris eu qui irure nulla qui culpa et. Cupidatat sunt ipsum proident aute exercitation do tempor aliqua cupidatat quis non exercitation. Adipisicing do minim dolore nulla mollit. Adipisicing incididunt irure ipsum et in esse ipsum elit tempor.Aliquip mollit sunt qui irure. Irure ullamco Lorem excepteur dolor qui ea ad quis. Enim fugiat cillum enim ad occaecat sint qui elit labore mollit sunt laborum fugiat consequat. Voluptate labore sunt duis eu deserunt. Occaecat do ut ut labore cillum enim dolore ad enim enim id. Aliquip do veniam ad excepteur ad cillum qui deserunt nostrud sunt aliqua duis sunt occaecat. Laborum incididunt commodo ullamco proident quis.",
  },
  {
    id: 1,
    image: ArticleImage,
    tags: ["career"],
    artistNickName: "arthurblack",
    tag: "FEATURED ARTICLE",
    title: "World’s Most Dangerous Technology Ever Made.",
    artist: "Arthur Black",
    date: "May 7, 2019",
    text: "Incididunt occaecat et qui dolore consectetur magna. Lorem veniam ut et labore consequat ut ex sunt. Ut et nostrud aliquip do anim proident ad nulla consectetur eu aute ex anim mollit. Anim aute exercitation nisi fugiat. Dolor velit excepteur commodo proident nulla commodo ullamco labore et esse.",
  },
  {
    id: 2,
    image: ArticleImage,
    tags: ["tech", "career"],
    artistNickName: "lesliePena",
    tag: "FEATURED ARTICLE",
    title: "World’s Most Dangerous Technology Ever Made.",
    artist: "Leslie Pena",
    date: "May 7, 2019",
    text: "Incididunt occaecat et qui dolore consectetur magna. Lorem veniam ut et labore consequat ut ex sunt. Ut et nostrud aliquip do anim proident ad nulla consectetur eu aute ex anim mollit. Anim aute exercitation nisi fugiat. Dolor velit excepteur commodo proident nulla commodo ullamco labore et esse.",
  },
  {
    id: 3,
    image: ArticleImage,
    artistNickName: "arthurblack",
    tag: "FEATURED ARTICLE",
    tags: ["technology", "tech", "career"],
    title: "Dolor ex Tempor Cotur Culpa li",
    artist: "Arthur Black",
    date: "May 7, 2019",
    text: "Sint anim Lorem aute duis Lorem incididunt. Nulla nostrud irure id ipsum aute excepteur duis sint. Do occaecat sit dolor magna esse. Mollit incididunt cillum consectetur fugiat adipisicing dolor est id minim amet cillum esse Lorem. Deserunt non duis excepteur aliqua duis eu reprehenderit.",
  },
];
